program GeN;

uses
  Forms,
  UFFormaPago in '..\..\..\SubOperacion\FormaPago\Form\UFFormaPago.pas' {FFormaPago},
  UFClientes in '..\..\..\ABM\Cliente\Form\UFClientes.pas' {FClientes},
  UFCategorias in '..\..\..\ABM\Categoria\Form\UFCategorias.pas' {FCategorias},
  UFBuscaProve in '..\..\..\Buscar\Proveedor\Form\UFBuscaProve.pas' {FBuscaProve},
  UFBuscaCliente in '..\..\..\Buscar\Cliente\Form\UFBuscaCliente.pas' {FBuscaCliente},
  AporteCapitalF in '..\..\..\Operacion\AporteCapital\Form\AporteCapitalF.pas' {AporteCapitalForm},
  AgregarCantidad in '..\..\..\SubOperacion\AgregarCantidad\Form\AgregarCantidad.pas' {AgregarCantidadForm},
  ActivarCelularF in '..\..\..\Operacion\ActivarCelular\Form\ActivarCelularF.pas' {VendedorActivaForm},
  ActivacionesLF in '..\..\..\Listados\Activaciones\Form\ActivacionesLF.pas' {ActivacionesLForm},
  ListarPedidoF in '..\..\..\Listados\Pedidos\Form\ListarPedidoF.pas' {ListarPedidoForm},
  ListadoClientes in '..\..\..\Listados\Clientes\Form\ListadoClientes.pas' {ListadoClientesForm},
  LibroIVAVentasF in '..\..\..\Listados\LibroIVAVentas\Form\LibroIVAVentasF.pas' {CuentasForm},
  LibroIVAComprasF in '..\..\..\Listados\LibroIVACompras\Form\LibroIVAComprasF.pas' {LibroIVAComprasForm},
  LibroDiarioF in '..\..\..\Listados\LibroDiario\Form\LibroDiarioF.pas' {LibroDiarioLForm},
  IngresoDineroF in '..\..\..\SubOperacion\IngresoDinero\Form\IngresoDineroF.pas' {IngresoDineroForm},
  incremento in '..\..\..\Operacion\IncrementarValorPorc\Form\incremento.pas' {IncrementoForm},
  ImpuestosServicios in '..\..\..\ABM\ImpuestoServicio\Form\ImpuestosServicios.pas' {ImpuestosServiciosFrom},
  ImprimirDM in '..\..\..\DataModule\ImprimirDM.pas' {ImprimirDataModule: TDataModule},
  Hoja_Calculo in '..\..\..\Exportar\Excel\Hoja_Calculo.pas',
  GestionCobranzaF in '..\..\..\Operacion\GestionCobranza\From\GestionCobranzaF.pas' {GestionCobranzaForm},
  GananciasL in '..\..\..\Listados\Ganancias\Form\GananciasL.pas' {GanaciaxVtaLForm},
  EstadoCuentaLF in '..\..\..\Listados\EstadoCuenta\Form\EstadoCuentaLF.pas' {EstadoCuentaLForm},
  Entrega in '..\..\..\SubOperacion\EntregaDinero\Form\Entrega.pas' {EntregaForm},
  EmpresaF in '..\..\..\ABM\Empresa\Form\EmpresaF.pas' {EmpresaForm},
  DevolucionProveedorCelularF in '..\..\..\Operacion\DevolucionProveedorCelular\Form\DevolucionProveedorCelularF.pas' {DevolucionesForm},
  DataModule in '..\..\..\DataModule\DataModule.pas' {DM: TDataModule},
  CalculoCuotas in '..\..\..\SubOperacion\CalculoCuotas\Form\CalculoCuotas.pas' {CalculoCuotasForm},
  ListadoCuentasF in '..\..\..\Listados\Cuentas\Form\ListadoCuentasF.pas' {ListadoCuentasForm},
  CuentaContableF in '..\..\..\ABM\CuentaContable\Form\CuentaContableF.pas' {CuentasContablesForm},
  CtaCteProveedores in '..\..\..\Operacion\PagoProveedor\Form\CtaCteProveedores.pas' {CtaCteProveedoresForm},
  CtaCteF in '..\..\..\Operacion\CtaCte\Form\CtaCteF.pas' {CtaCteForm},
  CrearPedidoF in '..\..\..\Operacion\CrearPedido\Form\CrearPedidoF.pas' {CrearPedidoForm},
  CrearCreditoF in '..\..\..\Operacion\CrearCredito\Form\CrearCreditoF.pas' {CrearCreditoForm},
  ConfigurarF in '..\..\..\SubOperacion\BackUp\Form\ConfigurarF.pas' {ConfigurarForm},
  ConfiguracionF in '..\..\..\Configuracion\Sistema\Form\ConfiguracionF.pas' {ConfiguracionForm},
  ComprarF in '..\..\..\Operacion\Comprar\Form\ComprarF.pas' {ComprarForm},
  ComprarCelularF in '..\..\..\Operacion\ComprarCelular\Form\ComprarCelularF.pas' {ComprarCelularForm},
  Color in '..\..\..\ABM\Color\Form\Color.pas' {ColorForm},
  CobranzaJudicialF in '..\..\..\Operacion\GestionCobranzaJudicial\Form\CobranzaJudicialF.pas' {CobranzaJudicialForm},
  CobranzaIncobrableF in '..\..\..\Operacion\GestionCobranzaIncobrable\Form\CobranzaIncobrableF.pas' {CobranzaIncobrableForm},
  CobranzaExtraJudicialF in '..\..\..\Operacion\GestionCobranzaExtraJudicial\Form\CobranzaExtraJudicialF.pas' {CobranzaExtraJudicialForm},
  CobradorF in '..\..\..\ABM\Cobrador\Form\CobradorF.pas' {CobradorForm},
  CartonCobranzaF in '..\..\..\Listados\CartonCobranza\Form\CartonCobranzaF.pas' {CartonCobranzaForm},
  CapituloF in '..\..\..\ABM\Capitulo\Form\CapituloF.pas' {CapituloForm},
  CajaLF in '..\..\..\Listados\Caja\Form\CajaLF.pas' {CajaLForm},
  CajaF in '..\..\..\ABM\Caja\Form\CajaF.pas' {ABMCajaForm},
  BuscaSocioF in '..\..\..\Buscar\Socio\Form\BuscaSocioF.pas' {BuscaSocioForm},
  BuscarVendedor in '..\..\..\Buscar\Vendedor\Form\BuscarVendedor.pas' {BuscarVendedorForm},
  BuscarTipoGastoF in '..\..\..\Buscar\TipoGasto\Form\BuscarTipoGastoF.pas' {BuscarTipoGastoForm},
  BuscarRubroContableF in '..\..\..\Buscar\RubroContable\Form\BuscarRubroContableF.pas' {BuscarRubroContableForm},
  BuscarPlanFacturado in '..\..\..\Buscar\PlanProcesado\Form\BuscarPlanFacturado.pas' {BuscarPlanFacturadoForm},
  BuscarPlan in '..\..\..\Buscar\Plan\Form\BuscarPlan.pas' {BuscarPlanForm},
  BuscarImpuestosServicios in '..\..\..\Buscar\ImpuestoServicio\Form\BuscarImpuestosServicios.pas' {BuscarImpuestosServiciosForm},
  BuscarCuentaF in '..\..\..\Buscar\CuentaContable\Form\BuscarCuentaF.pas' {BuscarCuentaForm},
  BuscarCobrador in '..\..\..\Buscar\Cobrador\Form\BuscarCobrador.pas' {BuscarCobradorForm},
  BuscarCheques in '..\..\..\Buscar\Cheque\Form\BuscarCheques.pas' {BuscarChequesForm},
  BuscarCapituloF in '..\..\..\Buscar\Capitulo\Form\BuscarCapituloF.pas' {BuscarCapituloForm},
  UFBuscaArticulos in '..\..\..\Buscar\Articulo\Form\UFBuscaArticulos.pas' {FBuscaArticulo},
  Cuotas in '..\..\..\ABM\Cuota\Form\Cuotas.pas' {CuotaForm},
  AnularVtaF in '..\..\..\Operacion\AnularVenta\Form\AnularVtaF.pas' {FAnulaReimp},
  TipoGastoF in '..\..\..\ABM\TipoGasto\Form\TipoGastoF.pas' {TipoGastoForm},
  StockF in '..\..\Stock\Form\StockF.pas' {StockForm},
  SocioF in '..\..\..\ABM\Socio\Form\SocioF.pas' {SocioForm},
  servicio in '..\..\..\SubOperacion\ManoObra\Form\servicio.pas' {ServForm},
  SeleccionarCelularF in '..\..\..\SubOperacion\SeleccionarCelular\Form\SeleccionarCelularF.pas' {SeleccionarCelularForm},
  SeleccionarCartonF in '..\..\..\SubOperacion\SeleccionarCarton\Form\SeleccionarCartonF.pas' {SeleccionarCartonForm},
  RubroF in '..\..\..\ABM\Rubro\Form\RubroF.pas' {RubroForm},
  RubroContableFormF in '..\..\..\ABM\RubroContable\Form\RubroContableFormF.pas' {RubroContableForm},
  RetiroCajaF in '..\..\..\Operacion\RetiroCaja\Form\RetiroCajaF.pas' {RetiroCajaForm},
  RendicionCobradorLF in '..\..\..\Listados\RendicionCobrador\Form\RendicionCobradorLF.pas' {RendicionCobradorLForm},
  RendicionClienteLF in '..\..\..\Listados\RendicionCliente\Form\RendicionClienteLF.pas' {RendicionClienteLForm},
  RendicionClienteF in '..\..\..\Operacion\RendicionCliente\Form\RendicionClienteF.pas' {RendicionClienteForm},
  RendicionCartonF in '..\..\..\Operacion\RendicionCarton\Form\RendicionCartonF.pas' {RendicionCartonForm},
  ProveedorF in '..\..\..\ABM\Proveedor\Form\ProveedorF.pas' {ProveedorForm},
  PresupuestoF in '..\..\..\Operacion\Presupuesto\Form\PresupuestoF.pas' {PresupuestoForm},
  Precios in '..\..\..\Listados\Precios\Form\Precios.pas' {ListaPreciosForm},
  PlanF in '..\..\..\ABM\Plan\Form\PlanF.pas' {PlanForm},
  PedidoLF in '..\..\..\Listados\Pedidos\Form\PedidoLF.pas' {PedidoLForm},
  PagoVendedorF in '..\..\..\Operacion\PagoVendedor\Form\PagoVendedorF.pas' {PagoVendedorForm},
  Pagos in '..\..\..\Operacion\PagoServicio\Form\Pagos.pas' {PagosForm},
  PagoIVAF in '..\..\..\Operacion\PagoIVA\Form\PagoIVAF.pas' {PagoIVAForm},
  PagoComisionCobrador in '..\..\..\Operacion\PagoCobrador\Form\PagoComisionCobrador.pas' {PagoComisionCobradorForm},
  OperacionDM in '..\..\..\DataModule\OperacionDM.pas' {OperacionDataModule: TDataModule},
  NotaCreditoPlanF in '..\..\..\Operacion\NotaCreditoPlan\Form\NotaCreditoPlanF.pas' {NotaCreditoPlanForm},
  MigrarF in '..\..\..\Operacion\Migrar\form\MigrarF.pas' {MigrarForm},
  BackUpF in '..\..\..\Operacion\BackUp\Form\BackUpF.pas' {BackUpForm},
  ArticuloCelularF in '..\..\..\ABM\ArticuloCelular\Form\ArticuloCelularF.pas' {ArticuloCelularForm},
  VendedorF in '..\..\..\ABM\Vendedor\Form\VendedorF.pas' {VendedorForm},
  VaciarBaseF in '..\..\..\Operacion\VaciarBase\Form\VaciarBaseF.pas' {VaciarBaseForm},
  UsuariosF in '..\..\..\ABM\Usuarios\Form\UsuariosF.pas' {UsuariosForm},
  Unit1 in '..\..\..\Exportar\Excel\Unit1.pas' {Form1},
  UFSubCategorias in '..\..\..\ABM\SubCategoria\Form\UFSubCategorias.pas' {FSubCategorias},
  UFSelProdFact in '..\..\..\SubOperacion\SelecionarPrecio\Form\UFSelProdFact.pas' {FSelProdFact},
  UFSelOrden in '..\..\..\Buscar\Orden\Form\UFSelOrden.pas' {FSelOrden},
  UFProductos in '..\..\..\ABM\Articulo\Form\UFProductos.pas' {FProductos},
  VerCobranza in '..\..\..\Buscar\Cobranza\Form\VerCobranza.pas' {VerCobranzaForm},
  VenderF in '..\..\..\Operacion\VenderCodBarra\Form\VenderF.pas' {VenderForm},
  ExportarExcelF in '..\..\..\Exportar\Excel\Form\ExportarExcelF.pas' {Menu1},
  main in '..\..\..\AcercaDe\form\main.pas' {mainForm},
  LoginF in '..\..\..\SubOperacion\Login\Form\LoginF.pas' {FLogin},
  FullMainF in '..\Form\FullMainF.pas' {FullMainForm},
  BuscaCompra in '..\..\..\buscar\compra\form\BuscaCompra.pas' {BuscaCompraForm},
  BuscaFactura in '..\..\..\Buscar\Venta\Form\BuscaFactura.pas' {BuscaFacturaForm},
  UFDevoluciones in '..\..\..\operacion\devolucion\form\UFDevoluciones.pas' {FDevoluciones},
  BuscarArticulosCelularF in '..\..\..\buscar\articulocelular\form\BuscarArticulosCelularF.pas' {BuscaArticuloCelularForm},
  MarcaF in '..\..\..\ABM\Marca\Form\MarcaF.pas' {MarcaForm},
  IngresosBrutosF in '..\..\..\abm\ingresosbrutos\form\IngresosBrutosF.pas' {IngresosBrutosForm},
  RestaurarBaseF in '..\..\..\Operacion\RestaurarBase\Form\RestaurarBaseF.pas' {RestaurarBaseForm};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'GeN';
  Application.CreateForm(TFullMainForm, FullMainForm);
  Application.CreateForm(TBuscaCompraForm, BuscaCompraForm);
  Application.CreateForm(TBuscaFacturaForm, BuscaFacturaForm);
  Application.CreateForm(TFDevoluciones, FDevoluciones);
  Application.CreateForm(TMarcaForm, MarcaForm);
  Application.CreateForm(TBuscaArticuloCelularForm, BuscaArticuloCelularForm);
  Application.CreateForm(TMarcaForm, MarcaForm);
  Application.CreateForm(TIngresosBrutosForm, IngresosBrutosForm);
  Application.CreateForm(TRestaurarBaseForm, RestaurarBaseForm);
  Application.Run;

end.
