SET SQL DIALECT 3;

CREATE DATABASE 'G:\DeGsoft\GeN\GEN.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET WIN1252;



/* Generators definitions */

CREATE GENERATOR "ActivarCelular_generator" ;
CREATE GENERATOR "Area_generator" ;
CREATE GENERATOR "Articulo_CODIGO_GEN" ;
CREATE GENERATOR "Banco_generator" ;
CREATE GENERATOR "Capitulo_generator" ;
CREATE GENERATOR "CartonCobranza_generator" ;
CREATE GENERATOR "Categoria_CODIGO_GEN" ;
CREATE GENERATOR "ChequeEntregado_generator" ;
CREATE GENERATOR "Cheque_generator" ;
CREATE GENERATOR "Cliente_CODIGO_GEN" ;
CREATE GENERATOR "Cliente_generator" ;
CREATE GENERATOR "Cobrador_generator" ;
CREATE GENERATOR "Cobranza_generator" ;
CREATE GENERATOR "Color_CODIGO_GEN" ;
CREATE GENERATOR "CompraItem_generator" ;
CREATE GENERATOR "Compra_generator" ;
CREATE GENERATOR "Concepto_generator" ;
CREATE GENERATOR "Config_generator" ;
CREATE GENERATOR "Contrato_generator" ;
CREATE GENERATOR "Control_generator" ;
CREATE GENERATOR "CtaCteItem_generator" ;
CREATE GENERATOR "CtaCte_generator" ;
CREATE GENERATOR "Devolucion_generator" ;
CREATE GENERATOR "Empresa_generator" ;
CREATE GENERATOR "FormaPago_generator" ;
CREATE GENERATOR "GestionCobranza_generator" ;
CREATE GENERATOR IG_CODIGO_GEN ;
CREATE GENERATOR IIBB_CODIGO_GEN ;
CREATE GENERATOR "Imprimir_generator" ;
CREATE GENERATOR "LibroBanco_generator" ;
CREATE GENERATOR "LibroDiario_generator" ;
CREATE GENERATOR "LibroIVAcompra_generator" ;
CREATE GENERATOR "LibroIVAventa_generator" ;
CREATE GENERATOR "Marca_CODIGO_GEN" ;
CREATE GENERATOR "Material_generator" ;
CREATE GENERATOR "NotaCredito_generator" ;
CREATE GENERATOR "Permiso_generator" ;
CREATE GENERATOR "Plan_generator" ;
CREATE GENERATOR "Proveedor_CODIGO_GEN" ;
CREATE GENERATOR "RendidoCobrador_generator" ;
CREATE GENERATOR "RendidoVendedor_generator" ;
CREATE GENERATOR "RubroContable_generator" ;
CREATE GENERATOR "Rubro_CODIGO_GEN" ;
CREATE GENERATOR "Socio_generator" ;
CREATE GENERATOR "StillActivacion_generator" ;
CREATE GENERATOR "SubCategoria_CODIGO_GEN" ;
CREATE GENERATOR "SubCategoria_generator" ;
CREATE GENERATOR "Tarjeta_generator" ;
CREATE GENERATOR "TipoCambio_generator" ;
CREATE GENERATOR "TipoGasto_generator" ;
CREATE GENERATOR "Tratado_generator" ;
CREATE GENERATOR "Usuario_generator" ;
CREATE GENERATOR "Vendedor_generator" ;
CREATE GENERATOR "VentaItem_generator" ;
CREATE GENERATOR "Venta_generator" ;
SET GENERATOR "ActivarCelular_generator" TO 0;

SET GENERATOR "Area_generator" TO 0;

SET GENERATOR "Articulo_CODIGO_GEN" TO 5;

SET GENERATOR "Banco_generator" TO 0;

SET GENERATOR "Capitulo_generator" TO 5;

SET GENERATOR "CartonCobranza_generator" TO 0;

SET GENERATOR "Categoria_CODIGO_GEN" TO 1;

SET GENERATOR "Cheque_generator" TO 0;

SET GENERATOR "ChequeEntregado_generator" TO 0;

SET GENERATOR "Cliente_CODIGO_GEN" TO 62768;

SET GENERATOR "Cliente_generator" TO 1;

SET GENERATOR "Cobrador_generator" TO 1;

SET GENERATOR "Cobranza_generator" TO 0;

SET GENERATOR "Color_CODIGO_GEN" TO 1;

SET GENERATOR "Compra_generator" TO 0;

SET GENERATOR "CompraItem_generator" TO 0;

SET GENERATOR "Concepto_generator" TO 0;

SET GENERATOR "Config_generator" TO 1;

SET GENERATOR "Contrato_generator" TO 0;

SET GENERATOR "Control_generator" TO 15;

SET GENERATOR "CtaCte_generator" TO 0;

SET GENERATOR "CtaCteItem_generator" TO 0;

SET GENERATOR "Devolucion_generator" TO 0;

SET GENERATOR "Empresa_generator" TO 1;

SET GENERATOR "FormaPago_generator" TO 0;

SET GENERATOR "GestionCobranza_generator" TO 0;

SET GENERATOR IG_CODIGO_GEN TO 0;

SET GENERATOR IIBB_CODIGO_GEN TO 1;

SET GENERATOR "Imprimir_generator" TO 10;

SET GENERATOR "LibroBanco_generator" TO 0;

SET GENERATOR "LibroDiario_generator" TO 0;

SET GENERATOR "LibroIVAcompra_generator" TO 0;

SET GENERATOR "LibroIVAventa_generator" TO 0;

SET GENERATOR "Marca_CODIGO_GEN" TO 1;

SET GENERATOR "Material_generator" TO 0;

SET GENERATOR "NotaCredito_generator" TO 0;

SET GENERATOR "Permiso_generator" TO 0;

SET GENERATOR "Plan_generator" TO 2;

SET GENERATOR "Proveedor_CODIGO_GEN" TO 2;

SET GENERATOR "RendidoCobrador_generator" TO 0;

SET GENERATOR "RendidoVendedor_generator" TO 0;

SET GENERATOR "Rubro_CODIGO_GEN" TO 1;

SET GENERATOR "RubroContable_generator" TO 15;

SET GENERATOR "Socio_generator" TO 2;

SET GENERATOR "StillActivacion_generator" TO 0;

SET GENERATOR "SubCategoria_CODIGO_GEN" TO 0;

SET GENERATOR "SubCategoria_generator" TO 1;

SET GENERATOR "Tarjeta_generator" TO 0;

SET GENERATOR "TipoCambio_generator" TO 0;

SET GENERATOR "TipoGasto_generator" TO 4;

SET GENERATOR "Tratado_generator" TO 0;

SET GENERATOR "Usuario_generator" TO 3;

SET GENERATOR "Vendedor_generator" TO 1;

SET GENERATOR "Venta_generator" TO 0;

SET GENERATOR "VentaItem_generator" TO 0;



/* External functions definition */

DECLARE EXTERNAL FUNCTION RDB$GET_CONTEXT 
    VARCHAR (80),
    VARCHAR (80)
    RETURNS VARCHAR (255) FREE_IT
    ENTRY_POINT 'get_context' MODULE_NAME 'system_module';


DECLARE EXTERNAL FUNCTION RDB$SET_CONTEXT 
    VARCHAR (80),
    VARCHAR (80),
    VARCHAR (255)
    RETURNS INTEGER BY VALUE
    ENTRY_POINT 'set_context' MODULE_NAME 'system_module';




/* Tables definitions */

CREATE TABLE "ActivarCelular" (
    CODIGO INTEGER,
    IMEI VARCHAR (50) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    NSE VARCHAR (50) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    "Vendedor" INTEGER,
    "Fecha" TIMESTAMP);

CREATE TABLE "Area" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    EMPRESA INTEGER);

CREATE TABLE "Articulo" (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    COSTO DOUBLE PRECISION,
    ULTCOSTO DOUBLE PRECISION,
    PRECIO1 DOUBLE PRECISION,
    PRECIO2 DOUBLE PRECISION,
    PRECIO3 DOUBLE PRECISION,
    PRECIO4 DOUBLE PRECISION,
    PRECIO5 DOUBLE PRECISION,
    PRECIO6 DOUBLE PRECISION,
    PRECIO DOUBLE PRECISION,
    PORCENTAJE DOUBLE PRECISION,
    ULTPRECIO DOUBLE PRECISION,
    MARCA INTEGER,
    COLOR INTEGER,
    CATEGORIA INTEGER,
    SUBCATEGORIA INTEGER,
    UBICACION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    UNIDAD VARCHAR (50) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    DISPONIBLE INTEGER,
    ENPRODUCCION INTEGER,
    NOTAS VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    IVA INTEGER,
    TASA INTEGER,
    IMPOTROS INTEGER,
    IIBB INTEGER,
    STOCKMINIMO INTEGER,
    STOCKMAXIMO INTEGER,
    STOCKVENDIDO INTEGER,
    FECHACOMPULT TIMESTAMP,
    LISTA INTEGER,
    PROCEDENCIA VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    CODIGOBARRA VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    RUBRO INTEGER,
    PROVEEDOR INTEGER,
    GARANTIA INTEGER,
    FECHA TIMESTAMP,
    PEDIDO INTEGER,
    STOCK VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    EXISTENTE INTEGER,
    ACTUAL INTEGER,
    MARCADOCONTADO INTEGER,
    MARCADOLISTA INTEGER,
    MARCADOFINAL INTEGER,
    PREPARADO VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    CTANOMBRE INTEGER,
    CTATIPO INTEGER,
    CTAANTICIPO INTEGER,
    CTAIIBB INTEGER,
    ESTADO VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    VENCE TIMESTAMP,
    VENCIMIENTO INTEGER);

CREATE TABLE "Banco" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    DIRECCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    CUENTA VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    CBU VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    TARJETA VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    NOTA VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    CTA INTEGER);

CREATE TABLE "Capitulo" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    TIPOGASTO INTEGER);

CREATE TABLE "CartonCobranza" (
    CODIGO INTEGER,
    OPERACION INTEGER,
    FECHA TIMESTAMP,
    IMPRESION INTEGER,
    USUARIO INTEGER);

CREATE TABLE "Categoria" (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Cheque" (
    CODIGO INTEGER,
    NUMERO VARCHAR (50) CHARACTER SET NONE COLLATE NONE,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    FACTURA VARCHAR (50) CHARACTER SET NONE COLLATE NONE,
    IMPORTE DOUBLE PRECISION,
    FECHA TIMESTAMP,
    DIAS INTEGER,
    CTA INTEGER);

CREATE TABLE "ChequeEntegado" (
    CODIGO INTEGER,
    CHEQUE INTEGER,
    NUMERO VARCHAR (50) CHARACTER SET NONE COLLATE NONE,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    FACTURA VARCHAR (50) CHARACTER SET NONE COLLATE NONE,
    IMPORTE DOUBLE PRECISION,
    FECHA TIMESTAMP,
    DIAS INTEGER,
    CTA INTEGER);

CREATE TABLE "Cliente" (
    CODIGO INTEGER NOT NULL,
    NOMBRE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    TITULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCIONCOMERCIAL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PAIS VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROVINCIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEPARTAMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CIUDAD VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    BARRIO VARCHAR (255) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    CP VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CODIGOAREA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CELULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TELEFONO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXTENCION VARCHAR (6) CHARACTER SET WIN1252 COLLATE WIN1252,
    FAX VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    EMAIL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TERMINOS VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR INTEGER,
    PRECIO INTEGER,
    SUSPENDIDO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXCENTO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHA TIMESTAMP,
    LIMITECREDITO DOUBLE PRECISION,
    NOTAS BLOB sub_type 0 segment size 80,
    DIASCREDITO INTEGER,
    DOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IIBB VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    RUBRO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IVA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MSN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    ALMANAQUES VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROMOCIONES VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    GARANTE INTEGER,
    ZONA INTEGER,
    CTA INTEGER,
    CTANOMBRE INTEGER,
    CTATIPO INTEGER,
    CTAANTICIPO INTEGER,
    PAGARE CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Cobrador" (
    CODIGO INTEGER,
    NOMBRE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    TITULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCIONCOMERCIAL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PAIS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROVINCIA VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEPARTAMENTO VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    CIUDAD VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    CP VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    CODIGOAREA VARCHAR (10) CHARACTER SET WIN1252 COLLATE WIN1252,
    CELULAR VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    TELEFONO VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXTENCION VARCHAR (6) CHARACTER SET WIN1252 COLLATE WIN1252,
    FAX VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    EMAIL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TERMINOS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR INTEGER,
    PRECIO INTEGER,
    SUSPENDIDO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXCENTO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHAINGRESO TIMESTAMP,
    LIMITECREDITO DOUBLE PRECISION,
    NOTAS BLOB sub_type 0 segment size 80,
    DIASCREDITO INTEGER,
    DOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    IIBB VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    RUBRO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IVA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MSN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    ALMANAQUES VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROMOCIONES VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    GARANTE INTEGER,
    ZONA INTEGER,
    CTA INTEGER,
    CTANOMBRE INTEGER,
    CTATIPO INTEGER,
    CTAANTICIPO INTEGER,
    PAGARE CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    COMISION DOUBLE PRECISION,
    PUNTOS DOUBLE PRECISION);

CREATE TABLE "Cobranza" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Color" (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Compra" (
    CODIGO INTEGER,
    LETRA CHAR (1) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHA TIMESTAMP,
    PROVEEDOR INTEGER,
    TERMINOS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    FACTURA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    REMITO VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR INTEGER,
    EXCENTO CHAR (1) CHARACTER SET WIN1252 COLLATE WIN1252,
    ANULADA CHAR (1) CHARACTER SET WIN1252 COLLATE WIN1252,
    SUBTOTAL DOUBLE PRECISION,
    DESCUENTO DOUBLE PRECISION,
    IMPUESTO DOUBLE PRECISION,
    IVA1 DOUBLE PRECISION,
    IVA2 DOUBLE PRECISION,
    IVA3 DOUBLE PRECISION,
    IIBB DOUBLE PRECISION,
    MINIMP DOUBLE PRECISION,
    TOTAL DOUBLE PRECISION,
    CONTADO DOUBLE PRECISION,
    CHEQUE DOUBLE PRECISION,
    TARJETA DOUBLE PRECISION,
    OTROS DOUBLE PRECISION,
    MONEDAEXTRANJERA INTEGER,
    MEIMPORTE DOUBLE PRECISION,
    METIPOCAMBIO DOUBLE PRECISION,
    SALDO DOUBLE PRECISION,
    PAGADO DOUBLE PRECISION,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    USUARIO INTEGER,
    EMPRESA INTEGER);

CREATE TABLE "CompraItem" (
    CODIGO INTEGER,
    COMPRA INTEGER,
    LINEA INTEGER,
    ARTICULO INTEGER,
    CANTIDAD DOUBLE PRECISION,
    COSTO DOUBLE PRECISION,
    PRECIO DOUBLE PRECISION,
    IMPUESTO DOUBLE PRECISION,
    SERVICIO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Concepto" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    PORCENTAJE DOUBLE PRECISION);

CREATE TABLE "Config" (
    CODIGO INTEGER,
    NROFACTURA INTEGER,
    "FechaInicio" VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PP1 DOUBLE PRECISION,
    PP2 DOUBLE PRECISION,
    PP3 DOUBLE PRECISION,
    PP4 DOUBLE PRECISION,
    PP5 DOUBLE PRECISION,
    PP6 DOUBLE PRECISION,
    PP7 DOUBLE PRECISION,
    PP8 DOUBLE PRECISION,
    PP9 DOUBLE PRECISION,
    PP DOUBLE PRECISION,
    "CtaCompra" INTEGER,
    "CtaMercaderia" INTEGER,
    "CtaIIBB" INTEGER,
    "CtaImpuesto" INTEGER,
    "CtaDeudor" INTEGER,
    "CtaVenta" INTEGER,
    "CtaCaja" INTEGER,
    "CtaAnticipoAProveedor" INTEGER,
    "CtaBanco" INTEGER,
    "CtaCMV" INTEGER,
    "CtaComisionVendedor" INTEGER,
    "CtaComisionVendedorAPagar" INTEGER,
    "CtaDeudorEnGestionJudicial" INTEGER,
    "CtaDeudorIncobrable" INTEGER,
    "CtaDeudorMoroso" INTEGER,
    "CtaDeudorPorVenta" INTEGER,
    "CtaDocumentoACobrar" INTEGER,
    "CtaHonorarioLegal" INTEGER,
    "CtaHonorarioLegalApagar" INTEGER,
    "CtaIVARemanente" INTEGER,
    "CtaIVAAPagar" INTEGER,
    "CtaIVACreditoFiscal" INTEGER,
    "CtaIVADebitoFiscal" INTEGER,
    "CtaLiquidacionDeIVA" INTEGER,
    "CtaMerRecJudicialmente" INTEGER,
    "CtaMercaderiaDeReventa" INTEGER,
    "CtaObligacionAPagar" INTEGER,
    "CtaPagoDeHonorario" INTEGER,
    "CtaTarjetaDeCredito" INTEGER,
    "CtaProveedor" INTEGER,
    "CtaRecuperoJudicial" INTEGER,
    "CtaServicioAPAgar" INTEGER,
    "CtaServicio" INTEGER,
    "CtaValorAlCobro" INTEGER,
    "CtaValorADepositar" INTEGER,
    "Cuenta" INTEGER,
    "Precio" INTEGER,
    "Comprobante" INTEGER,
    "Empresa" INTEGER,
    "ImprimirTipo" INTEGER,
    "Imprimir" CHAR (3) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    "ImprimirFiscal" CHAR (3) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    "ImprimirMostrar" CHAR (3) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    "CodigoBarra" CHAR (3) CHARACTER SET WIN1252 COLLATE PXW_INTL,
    "GesCobTemprana" INTEGER,
    "GesCobExtraJudicial" INTEGER,
    "GesCobJudicial" INTEGER,
    CMV INTEGER,
    CTACAPITALSOC INTEGER);

CREATE TABLE "Contrato" (
    CODIGO INTEGER,
    NUMERO INTEGER,
    FECHA TIMESTAMP,
    TIPO INTEGER,
    DIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DESCRITO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MES VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MESCRITO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    ANO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    AESCRITO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CANONES INTEGER,
    CIMPORTE DOUBLE PRECISION,
    CIESCRITO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IMPORTETOTAL DOUBLE PRECISION,
    ITESCRITO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TIEMPO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    T2 VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    BIEN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DADOR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DTIPO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DNOMBRE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DAPELLIDO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DDOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DDTIPO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DDOMICILIO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DDNUMERO INTEGER,
    DCIUDAD VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DPROVINCIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DPAIS VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TOMADOR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TTIPO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TNOMBRE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TAPELLIDO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TDOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TDTIPO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TDOMICILIO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TDTRABAJO VARCHAR (50) CHARACTER SET NONE COLLATE NONE,
    TCIUDAD VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TPROVINCIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TPAIS VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Control" (
    CODIGO INTEGER,
    USUARIO INTEGER,
    PERSONAL INTEGER,
    INICIO TIMESTAMP,
    FIN TIMESTAMP,
    MAQUINA VARCHAR (50) CHARACTER SET WIN1252 COLLATE PXW_INTL);

CREATE TABLE "CtaCte" (
    CODIGO INTEGER,
    FECHA TIMESTAMP,
    CLIENTE INTEGER,
    PROVEEDOR INTEGER,
    SALDO DOUBLE PRECISION,
    DESCRIPCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUOTAS INTEGER,
    RENDIDAS INTEGER,
    DESCUENTO DOUBLE PRECISION,
    INTERES DOUBLE PRECISION,
    COBRADOR INTEGER,
    OPERACION INTEGER,
    DETALLE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    ARTICULO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    COBRANZA INTEGER);

CREATE TABLE "CtaCteItem" (
    CODIGO INTEGER,
    PROVEEDOR INTEGER,
    CLIENTE INTEGER,
    OPERACION INTEGER,
    CUOTA INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    IMPORTE DOUBLE PRECISION,
    PAGADO DOUBLE PRECISION,
    VENCE DATE);

CREATE TABLE "Cuenta" (
    CODIGO INTEGER,
    RUBRO INTEGER,
    CAPITULO INTEGER,
    TIPOGASTO INTEGER,
    JERARQUIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DESCRIPCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    SALDO DOUBLE PRECISION,
    LEYENDADEUDORA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    LEYENDAHACREEDORA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Devolucion" (
    CODIGO INTEGER,
    FACTURA INTEGER,
    CLIENTE INTEGER,
    PROVEEDOR INTEGER,
    ARTICULO INTEGER,
    CANTIDAD INTEGER,
    IMPORTE INTEGER,
    FECHA TIMESTAMP,
    VENCIMIENTO TIMESTAMP,
    NOTAS BLOB sub_type 0 segment size 80);

CREATE TABLE "Empresa" (
    CODIGO INTEGER,
    NOMBRE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    TITULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCIONCOMERCIAL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PAIS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROVINCIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEPARTAMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CIUDAD VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    CP VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    CODIGOAREA VARCHAR (10) CHARACTER SET WIN1252 COLLATE WIN1252,
    CELULAR VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    TELEFONO VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    FAX VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    EMAIL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    SUSPENDIDO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXCENTO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHA TIMESTAMP,
    LIMITECREDITO DOUBLE PRECISION,
    NOTAS BLOB sub_type 0 segment size 80,
    DIASCREDITO INTEGER,
    DOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    RAZONSOCIAL VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    IIBB VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    RUBRO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IVA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MSN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    WEB VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    ZONA INTEGER,
    CTA INTEGER,
    CTANOMBRE INTEGER,
    CTATIPO INTEGER,
    CTAANTICIPO INTEGER,
    PAGARE CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "FormaPago" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENTA INTEGER,
    COMPRA INTEGER,
    CTACTE INTEGER,
    PAGOS INTEGER,
    CONTADO DOUBLE PRECISION,
    CHEQUE DOUBLE PRECISION,
    TARJETA DOUBLE PRECISION,
    OTROS DOUBLE PRECISION,
    MONEDAEXTRANJERA INTEGER,
    MEIMPORTE DOUBLE PRECISION,
    METIPOCAMBIO DOUBLE PRECISION,
    SALDO DOUBLE PRECISION,
    PAGADO DOUBLE PRECISION);

CREATE TABLE "GestionCobranza" (
    CODIGO INTEGER,
    FECHA DATE,
    HORA TIME,
    COBRANZA INTEGER,
    CLIENTE INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    NOTAS BLOB sub_type 0 segment size 80,
    RESPONDIO CHAR (3) CHARACTER SET WIN1252 COLLATE WIN1252,
    TRATADO INTEGER,
    VENTA INTEGER);

CREATE TABLE IG (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    NORETENIDO DOUBLE PRECISION,
    PORCENTAJE DOUBLE PRECISION,
    MONTO DOUBLE PRECISION);

CREATE TABLE IIBB (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    PORCENTAJE DOUBLE PRECISION,
    COEF1 DOUBLE PRECISION,
    COEF2 DOUBLE PRECISION,
    COEF3 DOUBLE PRECISION,
    MONTO DOUBLE PRECISION);

CREATE TABLE "Imprimir" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    REPORTE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "LibroBanco" (
    CODIGO INTEGER,
    FECHA TIMESTAMP,
    ORDEN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CHEQUE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CONCEPTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEBE DOUBLE PRECISION,
    HABER DOUBLE PRECISION);

CREATE TABLE "LibroDiario" (
    CODIGO INTEGER,
    ASIENTO INTEGER,
    FECHA TIMESTAMP,
    LEYENDA VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    JERARQUIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUENTA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEBE DOUBLE PRECISION,
    HABER DOUBLE PRECISION,
    OCULTO CHAR (3) CHARACTER SET WIN1252 COLLATE PXW_INTL);

CREATE TABLE "LibroIVAcompra" (
    CODIGO INTEGER,
    FECHA TIMESTAMP,
    FACTURA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROVEEDOR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CONDICION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    NG1 DOUBLE PRECISION,
    NG2 DOUBLE PRECISION,
    NG3 DOUBLE PRECISION,
    IVA1 DOUBLE PRECISION,
    IVA2 DOUBLE PRECISION,
    IVA3 DOUBLE PRECISION,
    OEIIBB DOUBLE PRECISION,
    IDERPYPAC DOUBLE PRECISION,
    ITF DOUBLE PRECISION);

CREATE TABLE "LibroIVAventa" (
    CODIGO INTEGER,
    FECHA TIMESTAMP,
    FACTURA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CLIENTE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CONDICION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    NG1 DOUBLE PRECISION,
    NG2 DOUBLE PRECISION,
    NG3 DOUBLE PRECISION,
    IVA1 DOUBLE PRECISION,
    IVA2 DOUBLE PRECISION,
    IVA3 DOUBLE PRECISION,
    OEIIBB DOUBLE PRECISION,
    IDERPYPAC DOUBLE PRECISION,
    ITF DOUBLE PRECISION);

CREATE TABLE "Marca" (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Material" (
    CODIGO INTEGER,
    ARTICULO INTEGER,
    EMPRESA INTEGER,
    CANTIDAD INTEGER);

CREATE TABLE "NotaCredito" (
    CODIGO INTEGER,
    FECHA DATE,
    HORA TIME,
    CLIENTE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    ARTICULO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IMPORTE DOUBLE PRECISION,
    VENCIMIENTO TIMESTAMP,
    VENTA INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    USUARIO INTEGER);

CREATE TABLE "Permiso" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    SECTOR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Plan" (
    CODIGO INTEGER,
    NOMBRE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    INTERES INTEGER,
    NUMEROHABIL INTEGER,
    NUMERONOHABIL INTEGER,
    DIASCALCULO INTEGER,
    TOTAL INTEGER);

CREATE TABLE "Proveedor" (
    CODIGO INTEGER NOT NULL,
    NOMBRE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    TITULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCIONCOMERCIAL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PAIS VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROVINCIA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEPARTAMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CIUDAD VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CP VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CODIGOAREA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CELULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TELEFONO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXTENCION VARCHAR (6) CHARACTER SET WIN1252 COLLATE WIN1252,
    FAX VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    EMAIL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TERMINOS VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR INTEGER,
    PRECIO INTEGER,
    SUSPENDIDO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXCENTO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHAINGRESO TIMESTAMP,
    LIMITECREDITO DOUBLE PRECISION,
    NOTAS BLOB sub_type 0 segment size 80,
    DIASCREDITO INTEGER,
    DOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IIBB VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    RUBRO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IVA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MSN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CONTACTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    GERENTE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    BANCO VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    CTACTE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    FORMADEPAGO INTEGER,
    VENCIMIENTO INTEGER,
    ZONA INTEGER,
    CTA INTEGER,
    CTANOMBRE INTEGER,
    CTATIPO INTEGER,
    CTAANTICIPO INTEGER,
    PAGARE CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "RendidoCobrador" (
    CODIGO INTEGER,
    COBRADOR INTEGER,
    VENTA INTEGER,
    CUOTA INTEGER,
    FECHA TIMESTAMP,
    RENDIDO DOUBLE PRECISION,
    PAGADO DOUBLE PRECISION,
    PROCESADO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "RendidoVendedor" (
    CODIGO INTEGER,
    VENDEDOR INTEGER,
    VENTA INTEGER,
    FECHA TIMESTAMP,
    IMPORTE DOUBLE PRECISION,
    PAGADO CHAR (3) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Rubro" (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "RubroContable" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Socio" (
    CODIGO INTEGER,
    NOMBRE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    TITULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCIONCOMERCIAL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PAIS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROVINCIA VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEPARTAMENTO VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    CIUDAD VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    CP VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    CODIGOAREA VARCHAR (10) CHARACTER SET WIN1252 COLLATE WIN1252,
    CELULAR VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    TELEFONO VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXTENCION VARCHAR (6) CHARACTER SET WIN1252 COLLATE WIN1252,
    FAX VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    EMAIL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TERMINOS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR INTEGER,
    PRECIO INTEGER,
    SUSPENDIDO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXCENTO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHAINGRESO TIMESTAMP,
    LIMITECREDITO DOUBLE PRECISION,
    NOTAS BLOB sub_type 0 segment size 80,
    DIASCREDITO INTEGER,
    DOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    IIBB VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    RUBRO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IVA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MSN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CONTACTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    GERENTE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    BANCO VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    CTACTE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    FORMADEPAGO INTEGER,
    VENCIMIENTO INTEGER,
    ZONA INTEGER,
    CTA INTEGER,
    CTANOMBRE INTEGER,
    CTATIPO INTEGER,
    CTAANTICIPO INTEGER,
    PAGARE CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "StillActivacion" (
    CODIGO INTEGER,
    STORE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    AGENTE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    SUBAGENTE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    COORDINADOR VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    DNIVENDEDOR VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    ENTIDAD VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    SDS VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    NIM VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    NSE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    IMEI VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUENTA VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    TITULAR VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    BLOQUE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    MERCADO VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    EQUIPO VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROMOCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    "Plan" VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    FORMAPAGO VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHAACTIV VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHAVENTA VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    PRESUSPENDIDA VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    POS VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    NOMBREPOS VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    CIUDADPOS VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    DPTOPCIAPOS VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "SubCategoria" (
    CODIGO INTEGER NOT NULL,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Tarjeta" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIAS INTEGER,
    PORCENTAJE DOUBLE PRECISION,
    TIPO CHAR (3) CHARACTER SET WIN1252 COLLATE PXW_INTL);

CREATE TABLE "TipoCambio" (
    CODIGO INTEGER,
    FECHA TIMESTAMP,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    IMPORTE DOUBLE PRECISION,
    USUARIO INTEGER);

CREATE TABLE "TipoGasto" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Tratado" (
    CODIGO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);

CREATE TABLE "Usuario" (
    CODIGO INTEGER,
    NOMBRE VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    "password" VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    PERMISO INTEGER,
    EMPRESA INTEGER);

CREATE TABLE "Vendedor" (
    CODIGO INTEGER,
    NOMBRE VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    TITULAR VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCION VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    DIRECCIONCOMERCIAL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PAIS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROVINCIA VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    DEPARTAMENTO VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    CIUDAD VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    CP VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    CODIGOAREA VARCHAR (10) CHARACTER SET WIN1252 COLLATE WIN1252,
    CELULAR VARCHAR (20) CHARACTER SET WIN1252 COLLATE WIN1252,
    TELEFONO VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXTENCION VARCHAR (6) CHARACTER SET WIN1252 COLLATE WIN1252,
    FAX VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    EMAIL VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    TERMINOS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR INTEGER,
    PRECIO INTEGER,
    SUSPENDIDO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    EXCENTO CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHAINGRESO TIMESTAMP,
    LIMITECREDITO DOUBLE PRECISION,
    NOTAS BLOB sub_type 0 segment size 80,
    DIASCREDITO INTEGER,
    DOCUMENTO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    CUIT VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    IIBB VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    RUBRO VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    IVA VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    MSN VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    ALMANAQUES VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    PROMOCIONES VARCHAR (50) CHARACTER SET WIN1252 COLLATE WIN1252,
    GARANTE INTEGER,
    ZONA INTEGER,
    CTA INTEGER,
    CTANOMBRE INTEGER,
    CTATIPO INTEGER,
    CTAANTICIPO INTEGER,
    PAGARE CHAR (2) CHARACTER SET WIN1252 COLLATE WIN1252,
    COMISION DOUBLE PRECISION,
    PUNTOS DOUBLE PRECISION);

CREATE TABLE "Venta" (
    CODIGO INTEGER,
    LETRA CHAR (1) CHARACTER SET WIN1252 COLLATE WIN1252,
    FECHA TIMESTAMP,
    CLIENTE INTEGER,
    TERMINOS VARCHAR (30) CHARACTER SET WIN1252 COLLATE WIN1252,
    COMPROBANTE VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    REMITO VARCHAR (15) CHARACTER SET WIN1252 COLLATE WIN1252,
    VENDEDOR INTEGER,
    EXCENTO CHAR (1) CHARACTER SET WIN1252 COLLATE WIN1252,
    ANULADA CHAR (1) CHARACTER SET WIN1252 COLLATE WIN1252,
    SUBTOTAL DOUBLE PRECISION,
    DESCUENTO DOUBLE PRECISION,
    IMPUESTO DOUBLE PRECISION,
    IVA1 DOUBLE PRECISION,
    IVA2 DOUBLE PRECISION,
    IVA3 DOUBLE PRECISION,
    IIBB DOUBLE PRECISION,
    MINIMP DOUBLE PRECISION,
    TOTAL DOUBLE PRECISION,
    CONTADO DOUBLE PRECISION,
    CHEQUE DOUBLE PRECISION,
    TARJETA DOUBLE PRECISION,
    OTROS DOUBLE PRECISION,
    MONEDAEXTRANJERA INTEGER,
    MEIMPORTE DOUBLE PRECISION,
    METIPOCAMBIO DOUBLE PRECISION,
    SALDO DOUBLE PRECISION,
    PAGADO DOUBLE PRECISION,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252,
    USUARIO INTEGER,
    EMPRESA INTEGER);

CREATE TABLE "VentaItem" (
    CODIGO INTEGER,
    VENTA INTEGER,
    LINEA INTEGER,
    ARTICULO INTEGER,
    CANTIDAD DOUBLE PRECISION,
    COSTO DOUBLE PRECISION,
    PRECIO DOUBLE PRECISION,
    IMPUESTO DOUBLE PRECISION,
    SERVICIO INTEGER,
    DESCRIPCION VARCHAR (255) CHARACTER SET WIN1252 COLLATE WIN1252);



/* Primary keys definition */

ALTER TABLE "Articulo" ADD CONSTRAINT "PK_Articulo" PRIMARY KEY (CODIGO);
ALTER TABLE "Categoria" ADD CONSTRAINT "PK_Categoria" PRIMARY KEY (CODIGO);
ALTER TABLE "Cliente" ADD CONSTRAINT "PK_Cliente" PRIMARY KEY (CODIGO);
ALTER TABLE "Color" ADD CONSTRAINT "PK_Color" PRIMARY KEY (CODIGO);
ALTER TABLE IG ADD CONSTRAINT PK_IG PRIMARY KEY (CODIGO);
ALTER TABLE IIBB ADD CONSTRAINT PK_IIBB PRIMARY KEY (CODIGO);
ALTER TABLE "Marca" ADD CONSTRAINT "PK_Marca" PRIMARY KEY (CODIGO);
ALTER TABLE "Proveedor" ADD CONSTRAINT "PK_Proveedor" PRIMARY KEY (CODIGO);
ALTER TABLE "Rubro" ADD CONSTRAINT "PK_Rubro" PRIMARY KEY (CODIGO);
ALTER TABLE "SubCategoria" ADD CONSTRAINT "PK_SubCategoria" PRIMARY KEY (CODIGO);


/* Foreign keys definition */

ALTER TABLE "Articulo" ADD CONSTRAINT FK_CATEGORIA FOREIGN KEY (CATEGORIA) REFERENCES "Categoria" (CODIGO);
ALTER TABLE "Articulo" ADD CONSTRAINT FK_COLOR FOREIGN KEY (COLOR) REFERENCES "Color" (CODIGO);
ALTER TABLE "Articulo" ADD CONSTRAINT FK_MARCA FOREIGN KEY (MARCA) REFERENCES "Marca" (CODIGO);
ALTER TABLE "Articulo" ADD CONSTRAINT FK_PROVEEDOR FOREIGN KEY (PROVEEDOR) REFERENCES "Proveedor" (CODIGO);
ALTER TABLE "Articulo" ADD CONSTRAINT FK_RUBRO FOREIGN KEY (RUBRO) REFERENCES "Rubro" (CODIGO);
ALTER TABLE "Articulo" ADD CONSTRAINT FK_SUBCATEGORIA FOREIGN KEY (SUBCATEGORIA) REFERENCES "SubCategoria" (CODIGO);


/* Indices definition */

CREATE INDEX FK_CATEGORIA ON "Articulo" (CATEGORIA);
CREATE INDEX FK_COLOR ON "Articulo" (COLOR);
CREATE INDEX FK_MARCA ON "Articulo" (MARCA);
CREATE INDEX FK_PROVEEDOR ON "Articulo" (PROVEEDOR);
CREATE INDEX FK_RUBRO ON "Articulo" (RUBRO);
CREATE INDEX FK_SUBCATEGORIA ON "Articulo" (SUBCATEGORIA);
CREATE INDEX "IDX_Contrato" ON "Contrato" (CODIGO);
CREATE INDEX "IDX_Control" ON "Control" (CODIGO, INICIO);
CREATE INDEX "IDX_CtaCte" ON "CtaCte" (CODIGO);
CREATE INDEX "IDX_Cuenta" ON "Cuenta" (CODIGO);
CREATE INDEX IDX_NOMBRE ON "Articulo" (DESCRIPCION);
CREATE UNIQUE INDEX "PK_ActivarCelular" ON "ActivarCelular" (CODIGO);
CREATE UNIQUE INDEX "PK_Area" ON "Area" (CODIGO);
CREATE UNIQUE INDEX "PK_Articulo" ON "Articulo" (CODIGO);
CREATE UNIQUE INDEX "PK_Banco" ON "Banco" (CODIGO);
CREATE UNIQUE INDEX "PK_Capitulo" ON "Capitulo" (CODIGO);
CREATE UNIQUE INDEX "PK_CartonCobranza" ON "CartonCobranza" (CODIGO);
CREATE UNIQUE INDEX "PK_Categoria" ON "Categoria" (CODIGO);
CREATE UNIQUE INDEX "PK_Cliente" ON "Cliente" (CODIGO);
CREATE UNIQUE INDEX "PK_Cobranza" ON "Cobranza" (CODIGO);
CREATE UNIQUE INDEX "PK_Color" ON "Color" (CODIGO);
CREATE UNIQUE INDEX "PK_Concepto" ON "Concepto" (CODIGO);
CREATE UNIQUE INDEX "PK_Devolucion" ON "Devolucion" (CODIGO);
CREATE UNIQUE INDEX "PK_FormaPago" ON "FormaPago" (CODIGO);
CREATE UNIQUE INDEX "PK_GestionCobranza" ON "GestionCobranza" (CODIGO);
CREATE UNIQUE INDEX PK_IG ON IG (CODIGO);
CREATE UNIQUE INDEX PK_IIBB ON IIBB (CODIGO);
CREATE UNIQUE INDEX "PK_LibroBanco" ON "LibroBanco" (CODIGO);
CREATE UNIQUE INDEX "PK_Marca" ON "Marca" (CODIGO);
CREATE UNIQUE INDEX "PK_Material" ON "Material" (CODIGO);
CREATE UNIQUE INDEX "PK_NotaCredito" ON "NotaCredito" (CODIGO);
CREATE UNIQUE INDEX "PK_Proveedor" ON "Proveedor" (CODIGO);
CREATE UNIQUE INDEX "PK_Rubro" ON "Rubro" (CODIGO);
CREATE UNIQUE INDEX "PK_RubroContable" ON "RubroContable" (CODIGO);
CREATE UNIQUE INDEX "PK_StillActivacion" ON "StillActivacion" (CODIGO);
CREATE UNIQUE INDEX "PK_SubCategoria" ON "SubCategoria" (CODIGO);
CREATE UNIQUE INDEX "PK_TipoCambio" ON "TipoCambio" (CODIGO);
CREATE UNIQUE INDEX "PK_TipoGasto" ON "TipoGasto" (CODIGO);
CREATE UNIQUE INDEX "PK_Tratado" ON "Tratado" (CODIGO);


SET TERM ^ ; 

/* Stored procedures definition */


/* Stored Procedure: "Articulo_CODIGO_AutoInc" */
CREATE PROCEDURE "Articulo_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "Categoria_CODIGO_AutoInc" */
CREATE PROCEDURE "Categoria_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "Cliente_CODIGO_AutoInc" */
CREATE PROCEDURE "Cliente_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "Color_CODIGO_AutoInc" */
CREATE PROCEDURE "Color_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "IG_CODIGO_AutoInc" */
CREATE PROCEDURE "IG_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "IIBB_CODIGO_AutoInc" */
CREATE PROCEDURE "IIBB_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "Marca_CODIGO_AutoInc" */
CREATE PROCEDURE "Marca_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "Proveedor_CODIGO_AutoInc" */
CREATE PROCEDURE "Proveedor_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "Rubro_CODIGO_AutoInc" */
CREATE PROCEDURE "Rubro_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


/* Stored Procedure: "SubCategoria_CODIGO_AutoInc" */
CREATE PROCEDURE "SubCategoria_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
AS
BEGIN
  EXIT;
END
^


ALTER PROCEDURE "Articulo_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "Categoria_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "Cliente_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "Color_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "IG_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "IIBB_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "Marca_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "Proveedor_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "Rubro_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


ALTER PROCEDURE "SubCategoria_CODIGO_AutoInc" 
RETURNS (
    NEW_VALUE INTEGER)
ASBEGIN
  EXIT;
END
^


SET TERM ; ^

SET TERM ^ ;

/* Triggers definition */



/* Trigger: "AI_Articulo_CODIGO" */
CREATE TRIGGER "AI_Articulo_CODIGO" FOR "Articulo" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("Articulo_CODIGO_GEN", 1);
  IF (NEW.PROVEEDOR IS NULL) THEN NEW.PROVEEDOR = 0 ;
  IF (NEW.COLOR IS NULL) THEN NEW.COLOR = 0 ;
  IF (NEW.MARCA IS NULL) THEN NEW.MARCA = 0 ;
  IF (NEW.CATEGORIA IS NULL) THEN NEW.CATEGORIA = 0 ;
  IF (NEW.SUBCATEGORIA IS NULL) THEN NEW.SUBCATEGORIA = 0 ;
  IF (NEW.RUBRO IS NULL) THEN NEW.RUBRO = 0 ;
  IF (NEW.IIBB IS NULL) THEN NEW.IIBB = 0 ;
END
^

/* Trigger: "AI_Categoria_CODIGO" */
CREATE TRIGGER "AI_Categoria_CODIGO" FOR "Categoria" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("Categoria_CODIGO_GEN", 1);
END
^

/* Trigger: "AI_Cliente_CODIGO" */
CREATE TRIGGER "AI_Cliente_CODIGO" FOR "Cliente" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("Cliente_CODIGO_GEN", 1);
END
^

/* Trigger: "AI_Color_CODIGO" */
CREATE TRIGGER "AI_Color_CODIGO" FOR "Color" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("Color_CODIGO_GEN", 1);
END
^

/* Trigger: AI_IG_CODIGO */
CREATE TRIGGER AI_IG_CODIGO FOR IG ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(IG_CODIGO_GEN, 1);
END
^

/* Trigger: AI_IIBB_CODIGO */
CREATE TRIGGER AI_IIBB_CODIGO FOR IIBB ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID(IIBB_CODIGO_GEN, 1);
END
^

/* Trigger: "AI_Marca_CODIGO" */
CREATE TRIGGER "AI_Marca_CODIGO" FOR "Marca" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("Marca_CODIGO_GEN", 1);
END
^

/* Trigger: "AI_Proveedor_CODIGO" */
CREATE TRIGGER "AI_Proveedor_CODIGO" FOR "Proveedor" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("Proveedor_CODIGO_GEN", 1);
END
^

/* Trigger: "AI_Rubro_CODIGO" */
CREATE TRIGGER "AI_Rubro_CODIGO" FOR "Rubro" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("Rubro_CODIGO_GEN", 1);
END
^

/* Trigger: "AI_SubCategoria_CODIGO" */
CREATE TRIGGER "AI_SubCategoria_CODIGO" FOR "SubCategoria" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODIGO IS NULL) THEN
      NEW.CODIGO = GEN_ID("SubCategoria_CODIGO_GEN", 1);
END
^

/* Trigger: "Banco_BI" */
CREATE TRIGGER "Banco_BI" FOR "Banco" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Banco_generator",1); END
^

/* Trigger: "Capitulo_BI" */
CREATE TRIGGER "Capitulo_BI" FOR "Capitulo" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Capitulo_generator",1); END
^

/* Trigger: "CartonCobranzaFecha_BI" */
CREATE TRIGGER "CartonCobranzaFecha_BI" FOR "CartonCobranza" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
     new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "CartonCobranza_BI" */
CREATE TRIGGER "CartonCobranza_BI" FOR "CartonCobranza" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("CartonCobranza_generator",1); END
^

/* Trigger: "ChequeEntegado_BI" */
CREATE TRIGGER "ChequeEntegado_BI" FOR "ChequeEntegado" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("ChequeEntregado_generator",1); END
^

/* Trigger: "Cheque_BI" */
CREATE TRIGGER "Cheque_BI" FOR "Cheque" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Cheque_generator",1); END
^

/* Trigger: "Cobrador_BI" */
CREATE TRIGGER "Cobrador_BI" FOR "Cobrador" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Cobrador_generator",1); END
^

/* Trigger: "Cobranza_BI" */
CREATE TRIGGER "Cobranza_BI" FOR "Cobranza" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Cobranza_generator",1); END
^

/* Trigger: "CompraFecha_BI" */
CREATE TRIGGER "CompraFecha_BI" FOR "Compra" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  /* Trigger body */
       new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "CompraItem_BI" */
CREATE TRIGGER "CompraItem_BI" FOR "CompraItem" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("CompraItem_generator",1); END
^

/* Trigger: "Compra_BI" */
CREATE TRIGGER "Compra_BI" FOR "Compra" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Compra_generator",1); END
^

/* Trigger: "Concepto_BI" */
CREATE TRIGGER "Concepto_BI" FOR "Concepto" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Concepto_generator",1); END
^

/* Trigger: "Config_BI" */
CREATE TRIGGER "Config_BI" FOR "Config" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Config_generator",1); END
^

/* Trigger: "ContratoFECHA_BI" */
CREATE TRIGGER "ContratoFECHA_BI" FOR "Contrato" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
  new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "Contrato_BI" */
CREATE TRIGGER "Contrato_BI" FOR "Contrato" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  /* Trigger body */
  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Contrato_generator",1);
END
^

/* Trigger: "ControlFIN_BI" */
CREATE TRIGGER "ControlFIN_BI" FOR "Control" ACTIVE
BEFORE UPDATE POSITION 2
AS
BEGIN
  /* Trigger body */
       new."FIN" = cast( 'now' as timestamp);
END
^

/* Trigger: "ControlINICIO_BI" */
CREATE TRIGGER "ControlINICIO_BI" FOR "Control" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
       new."INICIO" = cast( 'now' as timestamp);
END
^

/* Trigger: "Control_BI" */
CREATE TRIGGER "Control_BI" FOR "Control" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Control_generator",1); END
^

/* Trigger: "CtaCteFecha_BI" */
CREATE TRIGGER "CtaCteFecha_BI" FOR "CtaCte" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
     new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "CtaCteItem_BI" */
CREATE TRIGGER "CtaCteItem_BI" FOR "CtaCteItem" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("CtaCteItem_generator",1); END
^

/* Trigger: "CtaCte_BI" */
CREATE TRIGGER "CtaCte_BI" FOR "CtaCte" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("CtaCte_generator",1); END
^

/* Trigger: "Devolucion_BI" */
CREATE TRIGGER "Devolucion_BI" FOR "Devolucion" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Devolucion_generator",1); END
^

/* Trigger: "Empresa_BI" */
CREATE TRIGGER "Empresa_BI" FOR "Empresa" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Empresa_generator",1); END
^

/* Trigger: "FormaPago_BI" */
CREATE TRIGGER "FormaPago_BI" FOR "FormaPago" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("FormaPago_generator",1); END
^

/* Trigger: "GestionCobranza_BI" */
CREATE TRIGGER "GestionCobranza_BI" FOR "GestionCobranza" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("GestionCobranza_generator",1); END
^

/* Trigger: "Imprimir_BI" */
CREATE TRIGGER "Imprimir_BI" FOR "Imprimir" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Imprimir_generator",1); END
^

/* Trigger: "LibroBanco_BI" */
CREATE TRIGGER "LibroBanco_BI" FOR "LibroBanco" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("LibroBanco_generator",1); END
^

/* Trigger: "LibroDiarioFecha_BI" */
CREATE TRIGGER "LibroDiarioFecha_BI" FOR "LibroDiario" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
     new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "LibroDiario_BI" */
CREATE TRIGGER "LibroDiario_BI" FOR "LibroDiario" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("LibroDiario_generator",1); END
^

/* Trigger: "LibroIVAcompraFecha_BI" */
CREATE TRIGGER "LibroIVAcompraFecha_BI" FOR "LibroIVAcompra" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
     new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "LibroIVAcompra_BI" */
CREATE TRIGGER "LibroIVAcompra_BI" FOR "LibroIVAcompra" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("LibroIVAcompra_generator",1); END
^

/* Trigger: "LibroIVAventaFecha_BI" */
CREATE TRIGGER "LibroIVAventaFecha_BI" FOR "LibroIVAventa" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
     new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "LibroIVAventa_BI" */
CREATE TRIGGER "LibroIVAventa_BI" FOR "LibroIVAventa" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("LibroIVAventa_generator",1); END
^

/* Trigger: "Material_BI" */
CREATE TRIGGER "Material_BI" FOR "Material" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Material_generator",1); END
^

/* Trigger: "NotaCredito_BI" */
CREATE TRIGGER "NotaCredito_BI" FOR "NotaCredito" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("NotaCredito_generator",1); END
^

/* Trigger: "Permiso_BI" */
CREATE TRIGGER "Permiso_BI" FOR "Permiso" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Permiso_generator",1); END
^

/* Trigger: "Plan_BI" */
CREATE TRIGGER "Plan_BI" FOR "Plan" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Plan_generator",1); END
^

/* Trigger: "RendidoCobrador_BI" */
CREATE TRIGGER "RendidoCobrador_BI" FOR "RendidoCobrador" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("RendidoCobrador_generator",1); END
^

/* Trigger: "RendidoVendedorFecha_BI" */
CREATE TRIGGER "RendidoVendedorFecha_BI" FOR "RendidoVendedor" ACTIVE
BEFORE INSERT POSITION 1
AS
BEGIN
  /* Trigger body */
     new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "RendidoVendedorPagado_BI" */
CREATE TRIGGER "RendidoVendedorPagado_BI" FOR "RendidoVendedor" ACTIVE
BEFORE INSERT POSITION 2
AS BEGIN   /* Trigger body */  if (new."PAGADO" is null ) then  new."PAGADO" = 'NO'; END
^

/* Trigger: "RendidoVendedor_BI" */
CREATE TRIGGER "RendidoVendedor_BI" FOR "RendidoVendedor" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("RendidoVendedor_generator",1); END
^

/* Trigger: "RubroContable_BI" */
CREATE TRIGGER "RubroContable_BI" FOR "RubroContable" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("RubroContable_generator",1); END
^

/* Trigger: "Socio_BI" */
CREATE TRIGGER "Socio_BI" FOR "Socio" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Socio_generator",1); END
^

/* Trigger: "StillActivacion_BI" */
CREATE TRIGGER "StillActivacion_BI" FOR "StillActivacion" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("StillActivacion_generator",1); END
^

/* Trigger: "Tarjeta_BI" */
CREATE TRIGGER "Tarjeta_BI" FOR "Tarjeta" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Tarjeta_generator",1); END
^

/* Trigger: "TipoCambio_BI" */
CREATE TRIGGER "TipoCambio_BI" FOR "TipoCambio" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("TipoCambio_generator",1); END
^

/* Trigger: "TipoGasto_BI" */
CREATE TRIGGER "TipoGasto_BI" FOR "TipoGasto" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("TipoGasto_generator",1); END
^

/* Trigger: "Tratado_BI" */
CREATE TRIGGER "Tratado_BI" FOR "Tratado" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Tratado_generator",1); END
^

/* Trigger: "Usuario_BI" */
CREATE TRIGGER "Usuario_BI" FOR "Usuario" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Usuario_generator",1); END
^

/* Trigger: "Vendedor_BI" */
CREATE TRIGGER "Vendedor_BI" FOR "Vendedor" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Vendedor_generator",1); END
^

/* Trigger: "VentaFecha_BI" */
CREATE TRIGGER "VentaFecha_BI" FOR "Venta" ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  /* Trigger body */
     new."FECHA" = cast( 'now' as timestamp);
END
^

/* Trigger: "VentaItem_BI" */
CREATE TRIGGER "VentaItem_BI" FOR "VentaItem" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("VentaItem_generator",1); END
^

/* Trigger: "Venta_BI" */
CREATE TRIGGER "Venta_BI" FOR "Venta" ACTIVE
BEFORE INSERT POSITION 0
AS BEGIN   /* Trigger body */  if (new."CODIGO" is null ) then  new."CODIGO" = gen_id("Venta_generator",1); END
^

SET TERM ; ^
CREATE ROLE RDB$ADMIN;
